// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Recompose(arg1) {
  return window['go']['main']['App']['Recompose'](arg1);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2);
}

export function Split(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Split'](arg1, arg2, arg3, arg4);
}

export function UploadFile() {
  return window['go']['main']['App']['UploadFile']();
}
