// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Recompose(arg1:Array<string>):Promise<string>;

export function Split(arg1:string,arg2:number,arg3:number,arg4:string):Promise<string>;
